import 'dotenv/config';
import request from 'supertest';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { PrismaClient } from '@prisma/client';
import { createApp } from '../src/server';

const prisma = new PrismaClient(); const app = createApp(); const unique = Date.now();
let adminCookie='',barberCookie='',barberId='',clientId='',serviceId='',appointmentId='',blockId='',expenseId='',closingId='';

describe('API integrada',()=>{
 beforeAll(async()=>{
  const login=await request(app).post('/auth/login').send({email:process.env.SEED_ADMIN_EMAIL,password:process.env.SEED_ADMIN_PASSWORD}).expect(200);adminCookie=login.headers['set-cookie'][0].split(';')[0];
  const barber=await request(app).post('/users').set('Cookie',adminCookie).send({name:`Teste RBAC ${unique}`,email:`rbac${unique}@example.local`,password:'test-password-12345',commission:37,workStart:'09:00',workEnd:'19:00'}).expect(201);barberId=barber.body.id;
  const loginBarber=await request(app).post('/auth/login').send({email:`rbac${unique}@example.local`,password:'test-password-12345'}).expect(200);barberCookie=loginBarber.headers['set-cookie'][0].split(';')[0];
  const client=await request(app).post('/clients').set('Cookie',adminCookie).send({name:`Cliente API ${unique}`,phone:'5511999999999'}).expect(201);clientId=client.body.id;
  const service=await request(app).post('/services').set('Cookie',adminCookie).send({name:`Serviço API ${unique}`,duration:45,price:80,description:'Teste integrado'}).expect(201);serviceId=service.body.id;
 });
 it('protege autenticação e finanças globais por RBAC',async()=>{await request(app).get('/finance/dashboard').expect(401);const now=new Date(),to=new Date(now.getTime()+86400000);await request(app).get(`/finance/dashboard?from=${encodeURIComponent(now.toISOString())}&to=${encodeURIComponent(to.toISOString())}`).set('Cookie',barberCookie).expect(403);});
 it('bloqueia indisponibilidades e conflitos de agenda',async()=>{const start=new Date(Date.now()+7*86400000);start.setUTCHours(15,0,0,0);const end=new Date(start.getTime()+3600000);const block=await request(app).post('/schedule-blocks').set('Cookie',adminCookie).send({barberId,start:start.toISOString(),end:end.toISOString(),reason:'Folga de teste'}).expect(201);blockId=block.body.id;await request(app).post('/appointments').set('Cookie',adminCookie).send({barberId,clientId,serviceId,date:start.toISOString(),paymentMethod:'PIX'}).expect(409);await request(app).delete(`/schedule-blocks/${blockId}`).set('Cookie',adminCookie).expect(204);blockId='';const first=await request(app).post('/appointments').set('Cookie',adminCookie).send({barberId,clientId,serviceId,date:start.toISOString(),paymentMethod:'PIX'}).expect(201);appointmentId=first.body.id;await request(app).post('/appointments').set('Cookie',adminCookie).send({barberId,clientId,serviceId,date:new Date(start.getTime()+15*60000).toISOString(),paymentMethod:'PIX'}).expect(409);});
 it('preserva preço e calcula comissão pelo snapshot',async()=>{await request(app).patch(`/appointments/${appointmentId}/status`).set('Cookie',adminCookie).send({status:'CONCLUIDO',paymentMethod:'PIX'}).expect(200);const appointment=await prisma.appointment.findUniqueOrThrow({where:{id:appointmentId}});expect(Number(appointment.priceAtBooking)).toBe(80);expect(Number(appointment.commissionAtBooking)).toBe(37);const from=new Date(appointment.date.getTime()-60000),to=new Date(appointment.date.getTime()+60000);const report=await request(app).get(`/finance/dashboard?from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}`).set('Cookie',adminCookie).expect(200);const row=report.body.barbers.find((x:any)=>x.id===barberId);expect(row.gross).toBe(80);expect(row.commission).toBe(29.6);});
 it('permite ao barbeiro apenas a própria produção',async()=>{const appointment=await prisma.appointment.findUniqueOrThrow({where:{id:appointmentId}});const from=new Date(appointment.date.getTime()-60000),to=new Date(appointment.date.getTime()+60000);const own=await request(app).get(`/earnings/me?from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}`).set('Cookie',barberCookie).expect(200);expect(own.body.count).toBe(1);expect(own.body.commission).toBeCloseTo(29.6);});
 it('registra despesas, fecha caixa, consulta histórico e processa lembretes',async()=>{const expense=await request(app).post('/expenses').set('Cookie',adminCookie).send({description:'Material de teste',category:'Insumos',amount:12.5,date:new Date().toISOString(),paymentMethod:'PIX'}).expect(201);expenseId=expense.body.id;const closing=await request(app).post('/cash-closings').set('Cookie',adminCookie).send({businessDate:'2099-12-30',openingAmount:100,actualAmount:100,notes:'Teste automatizado'}).expect(201);closingId=closing.body.id;const history=await request(app).get(`/clients/${clientId}/history`).set('Cookie',adminCookie).expect(200);expect(history.body.appointments.some((x:any)=>x.id===appointmentId)).toBe(true);await prisma.appointmentReminder.updateMany({where:{appointmentId},data:{scheduledFor:new Date()}});const reminders=await request(app).post('/reminders/process').set('Cookie',adminCookie).expect(200);expect(reminders.body.processed).toBeGreaterThanOrEqual(1);expect(reminders.body.skipped).toBeGreaterThanOrEqual(1);});
 afterAll(async()=>{if(closingId)await prisma.cashClosing.delete({where:{id:closingId}});if(expenseId)await prisma.expense.delete({where:{id:expenseId}});if(appointmentId){await prisma.appointmentReminder.deleteMany({where:{appointmentId}});await prisma.appointment.delete({where:{id:appointmentId}})}if(blockId)await prisma.scheduleBlock.delete({where:{id:blockId}});if(clientId)await prisma.client.delete({where:{id:clientId}});if(serviceId)await prisma.service.delete({where:{id:serviceId}});if(barberId)await prisma.user.delete({where:{id:barberId}});await prisma.$disconnect();});
});
