'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowDownRight, ArrowRight, ArrowUpRight, BadgeCheck, Banknote, CalendarDays, ChevronLeft, ChevronRight, Clock3, LogOut, Menu, Plus, Scissors, Trash2, UsersRound, Wallet, X } from 'lucide-react';
import Skull from './Skull';
import Subscriptions from './Subscriptions';
import FinanceDashboard from './FinanceDashboard';
import { dateRange, money, monthRange, request } from '../lib/api';

type Section = 'agenda' | 'servicos' | 'barbeiros' | 'financeiro' | 'assinaturas' | 'cadastro';
type User = { id: string; name: string; email: string; phone?: string; role: 'ADMIN' | 'BARBEIRO'; commission: number | string; workStart: string; workEnd: string };
type Service = { id: string; name: string; description?: string; duration: number; price: number | string };
type Client = { id: string; name: string; phone?: string };
type Membership = { id: string; status: 'ATIVA'|'PAUSADA'|'CANCELADA'; clientId: string; client: Client; plan: { name: string }; visitsPerMonth: number; visitsUsed: number; includedServices: { id: string }[]; payments: { period: string; status: 'PENDENTE'|'PAGO' }[] };
type Status = 'AGENDADO' | 'EM_ANDAMENTO' | 'CONCLUIDO' | 'CANCELADO';
type Appointment = { id: string; date: string; status: Status; barberId: string; barber: User; client: Client; service: Service; subscriptionId?: string };
type Finance = { count: number; gross: number; serviceGross: number; subscriptionGross: number; byBarber: { id: string; name: string; count: number; gross: number; commission: number }[]; rows: { id: string; date: string; barber: string; service: string; price: number; type: 'SERVICE'|'SUBSCRIPTION' }[] };
const titles: Record<Section, string> = { agenda: 'Agenda diária', servicos: 'Serviços', barbeiros: 'Nossa equipe', financeiro: 'Financeiro', assinaturas: 'Clube de assinaturas', cadastro: 'Cadastrar barbeiro' };
const statuses: Status[] = ['AGENDADO', 'EM_ANDAMENTO', 'CONCLUIDO', 'CANCELADO'];
const statusLabels: Record<Status, string> = { AGENDADO: 'Agendado', EM_ANDAMENTO: 'Em andamento', CONCLUIDO: 'Concluído', CANCELADO: 'Cancelado' };
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const dateLabel = (day: string) => new Date(`${day}T12:00:00`).toLocaleDateString('pt-BR', { weekday: 'long', day: 'numeric', month: 'long' });
const timeLabel = (iso: string) => new Date(iso).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' });

export default function Dashboard({ section }: { section: Section }) {
  const router = useRouter();
  const [me, setMe] = useState<User | null>(null); const [loading, setLoading] = useState(true);
  const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [day, setDay] = useState(today); const [barbers, setBarbers] = useState<User[]>([]);
  const [services, setServices] = useState<Service[]>([]); const [clients, setClients] = useState<Client[]>([]);
  const [memberships, setMemberships] = useState<Membership[]>([]);
  const [appointments, setAppointments] = useState<Appointment[]>([]); const [finance, setFinance] = useState<Finance | null>(null); const [monthFinance, setMonthFinance] = useState<Finance | null>(null);
  const [modal, setModal] = useState<'appointment' | 'service' | 'barber' | 'client' | null>(null);
  const [editingService, setEditingService] = useState<Service | null>(null); const [editingBarber, setEditingBarber] = useState<User | null>(null);
  const [mobileNav, setMobileNav] = useState(false);
  useEffect(() => { const open = () => setModal('client'); document.addEventListener('barberflow:new-client', open); return () => document.removeEventListener('barberflow:new-client', open); }, []);
  const load = useCallback(async (user: User, selectedDay: string) => {
    try {
      const [b, s, a, f, mf, c, memberships] = await Promise.all([
        request<User[]>('/users'), request<Service[]>('/services'), request<Appointment[]>(`/appointments?${dateRange(selectedDay)}`),
        request<Finance>(`${user.role === 'ADMIN' ? '/finance' : '/earnings/me'}?${dateRange(selectedDay)}`), user.role === 'ADMIN' ? request<Finance>(`/finance?${monthRange(selectedDay)}`) : Promise.resolve(null),
        user.role === 'ADMIN' ? request<Client[]>('/clients') : Promise.resolve([]),
        user.role === 'ADMIN' && section === 'agenda' ? request<Membership[]>('/subscriptions') : Promise.resolve([])
      ]);
      setBarbers(b); setServices(s); setAppointments(a); setFinance(f); setMonthFinance(mf); setClients(c); setMemberships(memberships);
      setError('');
    } catch (e) { setError((e as Error).message); }
  }, [section]);
  useEffect(() => { request<{ user: User }>('/auth/me').then(async ({ user }) => { setMe(user); if (user.role === 'BARBEIRO' && section !== 'agenda') { router.replace('/agenda'); return; } await load(user, day); }).catch(() => router.replace('/login')).finally(() => setLoading(false)); }, [router, section, day, load]);
  useEffect(() => { if (!me || section !== 'agenda') return; const id = setInterval(() => load(me, day), 15000); return () => clearInterval(id); }, [me, section, day, load]);
  function changeDay(n: number) { const d = new Date(`${day}T12:00:00`); d.setDate(d.getDate()+n); setDay(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`); }
  async function logout() { await request('/auth/logout', { method: 'POST' }); router.push('/login'); }
  async function remove(path: string, label: string) { if (!confirm(`Remover ${label}?`)) return; try { await request(path, { method: 'DELETE' }); setNotice('Registro removido.'); await load(me!, day); } catch(e) { setError((e as Error).message); } }
  async function updateStatus(id: string, status: Status) { try { await request(`/appointments/${id}/status`, { method: 'PATCH', body: JSON.stringify({ status }) }); await load(me!, day); } catch(e) { setError((e as Error).message); } }
  if (loading || !me) return <div className="loading-screen"><Skull/><span>CARREGANDO BARBERFLOW...</span></div>;
  const isAdmin = me.role === 'ADMIN';
  const activeBarbers = barbers.filter(b => b.role === 'BARBEIRO');
  const completed = appointments.filter(a => a.status === 'CONCLUIDO').length;
  const nav = [{ href: '/agenda', label: 'Agenda', icon: CalendarDays }, { href: '/servicos', label: 'Serviços', icon: Scissors }, { href: '/barbeiros', label: 'Barbeiros', icon: UsersRound }, { href: '/assinaturas', label: 'Assinaturas', icon: BadgeCheck }, { href: '/financeiro', label: 'Financeiro', icon: Wallet }].filter(item => isAdmin || item.href === '/agenda');
  return <div className="shell">
    <aside className={`sidebar ${mobileNav ? 'open' : ''}`}><div className="side-brand"><Skull className="brand-skull"/><div><strong>BARBER<span>FLOW</span></strong><small>GESTÃO DE BARBEARIA</small></div></div><div className="side-divider"/><div className="side-caption">MENU PRINCIPAL</div><nav>{nav.map(item => <Link key={item.href} className={`nav-link ${item.href === `/${section}` ? 'active' : ''}`} href={item.href} onClick={() => setMobileNav(false)}><item.icon size={19}/>{item.label}{item.href === `/${section}` && <span className="nav-dot"/>}</Link>)}</nav><div className="side-bottom"><div className="side-quote"><Skull/><span>ESTILO É<br/>ATITUDE.</span><small>BARBERFLOW · 2026</small></div><button className="logout" onClick={logout}><LogOut size={17}/> Sair do sistema</button></div></aside>
    <main className="main"><header className="topbar"><button className="mobile-menu" onClick={() => setMobileNav(!mobileNav)}><Menu size={22}/></button><div className="breadcrumb">BARBERFLOW <span>/</span> <b>{titles[section].toUpperCase()}</b></div><div className="topbar-right"><span className="live-indicator"><i/> SISTEMA ONLINE</span><div className="user-avatar">{me.name.slice(0,1).toUpperCase()}</div><div className="topbar-user"><strong>{me.name}</strong><small>{isAdmin ? 'Administrador' : 'Barbeiro'}</small></div></div></header>
    <div className="content"><div className="page-heading"><div><div className="eyebrow"><span className="eyebrow-line"/> {isAdmin ? 'PAINEL DE CONTROLE' : 'MEU PAINEL'}</div><h1>{titles[section]}<span className="heading-star">✦</span></h1><p>{section === 'agenda' ? 'Tudo que acontece na cadeira, em um só lugar.' : section === 'servicos' ? 'O seu catálogo de experiências e cuidados.' : section === 'barbeiros' ? 'O talento por trás de cada transformação.' : section === 'financeiro' ? 'Os números que movimentam o seu negócio.' : section === 'assinaturas' ? 'Planos mensais, clientes fiéis e receita recorrente.' : 'Adicione um novo profissional à equipe.'}</p></div>{section === 'agenda' && isAdmin && <button className="button button-primary" onClick={() => setModal('appointment')}><Plus size={18}/> Novo agendamento</button>}{section === 'servicos' && isAdmin && <button className="button button-primary" onClick={() => { setEditingService(null); setModal('service'); }}><Plus size={18}/> Novo serviço</button>}{section === 'barbeiros' && isAdmin && <button className="button button-primary" onClick={() => { setEditingBarber(null); setModal('barber'); }}><Plus size={18}/> Novo barbeiro</button>}</div>
    {error && <div className="alert error">{error}<button onClick={() => setError('')}><X size={16}/></button></div>}{notice && <div className="alert success">{notice}<button onClick={() => setNotice('')}><X size={16}/></button></div>}
    {section === 'agenda' && <><div className="toolbar"><div className="day-selector"><button onClick={()=>changeDay(-1)} aria-label="Dia anterior"><ChevronLeft size={18}/></button><div><CalendarDays size={17}/><span>{dateLabel(day)}</span></div><button onClick={()=>changeDay(1)} aria-label="Próximo dia"><ChevronRight size={18}/></button></div><button className="today-button" onClick={()=>setDay(today())}>Hoje</button><span className="toolbar-note"><i/> Atualização a cada 15 segundos</span></div><div className="stats-grid"><Stat label="AGENDAMENTOS" value={String(appointments.filter(a=>a.status!=='CANCELADO').length).padStart(2,'0')} sub="no dia selecionado" icon={<CalendarDays size={21}/>} /><Stat label="CONCLUÍDOS" value={String(completed).padStart(2,'0')} sub="atendimentos finalizados" icon={<Scissors size={21}/>} /><Stat label={isAdmin ? 'FATURAMENTO DO DIA' : 'MINHA PRODUÇÃO'} value={money(finance?.gross || 0)} sub="serviços concluídos" icon={<Wallet size={21}/>} compact /></div><div className="section-title"><div><h2>Agenda por barbeiro</h2><p>Visão completa dos atendimentos</p></div><span>{activeBarbers.length} PROFISSIONAL{activeBarbers.length!==1?'S':''}</span></div><div className="agenda-grid">{activeBarbers.length ? activeBarbers.map(barber => { const list = appointments.filter(a=>a.barberId===barber.id); return <div className="barber-column" key={barber.id}><div className="column-header"><div className="avatar large">{barber.name.slice(0,1)}</div><div><strong>{barber.name}</strong><small><Clock3 size={12}/>{barber.workStart}–{barber.workEnd}</small></div><span className="column-count">{list.length}</span></div><div className="appointment-list">{list.length ? list.map(a => <div className={`appointment-card status-${a.status.toLowerCase()}`} key={a.id}><div className="appointment-top"><span>{timeLabel(a.date)}</span><span className="status-pill">{statusLabels[a.status]}</span></div><strong>{a.client.name}</strong><small>{a.service.name} · {a.service.duration} min{a.subscriptionId ? ' · Assinatura' : ''}</small><div className="appointment-bottom"><span>{a.subscriptionId ? 'Incluído no plano' : money(a.service.price)}</span><select aria-label="Alterar status" value={a.status} onChange={e=>updateStatus(a.id,e.target.value as Status)}>{statuses.map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select></div></div>) : <div className="empty-column"><Scissors size={28}/><strong>Agenda livre</strong><p>Sem agendamentos para este dia.</p></div>}</div></div>; }) : <div className="empty-wide"><UsersRound size={32}/><h3>Nenhum barbeiro cadastrado</h3><p>Cadastre a equipe para começar a organizar a agenda.</p>{isAdmin && <button className="button button-secondary" onClick={()=>setModal('barber')}>Cadastrar barbeiro</button>}</div>}</div></>}
    {section === 'servicos' && <><div className="section-title"><div><h2>Catálogo de serviços</h2><p>Preços, duração e detalhes do atendimento</p></div><span>{services.length} SERVIÇO{services.length!==1?'S':''}</span></div><div className="service-grid">{services.map((s,i)=><article className="service-card" key={s.id}><div className="service-number">0{i+1}</div><div className="service-icon"><Scissors size={26}/></div><h3>{s.name}</h3><p>{s.description || 'Um atendimento com a qualidade da casa.'}</p><div className="service-meta"><span><Clock3 size={15}/>{s.duration} min</span><strong>{money(s.price)}</strong></div><div className="card-actions"><button onClick={()=>{ setEditingService(s); setModal('service'); }}>Editar <ArrowRight size={15}/></button><button className="icon-danger" onClick={()=>remove(`/services/${s.id}`, s.name)} aria-label={`Remover ${s.name}`}><Trash2 size={16}/></button></div></article>)}{services.length===0 && <div className="empty-wide"><Scissors/><h3>Seu catálogo está vazio</h3><p>Adicione o primeiro serviço.</p></div>}</div></>}
    {section === 'barbeiros' && <><div className="section-title"><div><h2>Profissionais da casa</h2><p>Equipe, expediente e comissão</p></div><span>{activeBarbers.length} PROFISSIONAL{activeBarbers.length!==1?'S':''}</span></div><div className="team-grid">{activeBarbers.map((b,i)=><article className="team-card" key={b.id}><div className="team-index">0{i+1} / EQUIPE</div><div className="team-avatar">{b.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><h3>{b.name}</h3><p>{b.email}</p><div className="team-details"><div><Clock3 size={16}/><span>Expediente</span><strong>{b.workStart} – {b.workEnd}</strong></div><div><Banknote size={16}/><span>Comissão</span><strong>{Number(b.commission)}%</strong></div></div><div className="card-actions"><button onClick={()=>{setEditingBarber(b);setModal('barber');}}>Editar profissional <ArrowRight size={15}/></button><button className="icon-danger" onClick={()=>remove(`/users/${b.id}`, b.name)} aria-label={`Remover ${b.name}`}><Trash2 size={16}/></button></div></article>)}{activeBarbers.length===0 && <div className="empty-wide"><UsersRound/><h3>Sua equipe começa aqui</h3><p>Cadastre os barbeiros da casa.</p></div>}</div></>}
    {section === 'financeiro' && isAdmin && <FinanceDashboard/>}
    {section === 'assinaturas' && <Subscriptions/>}
    {section === 'cadastro' && <div className="form-page"><div className="form-page-art"><Skull/><span>UM NOVO TALENTO<br/>NA CADEIRA.</span></div><div className="form-page-copy"><h2>Amplie seu time.</h2><p>Cadastre um profissional para disponibilizar a agenda e acompanhar seus rendimentos.</p><button className="button button-primary" onClick={()=>{setEditingBarber(null);setModal('barber');}}><Plus size={18}/> Cadastrar barbeiro</button></div></div>}
    </div></main>{modal && <EditorModal type={modal} editingService={editingService} editingBarber={editingBarber} barbers={activeBarbers} services={services} clients={clients} memberships={memberships} day={day} onClose={()=>setModal(null)} onSaved={async (message)=>{setModal(null);setNotice(message);await load(me,day);}} onClientCreated={client=>{setClients(prev=>[...prev,client]);setModal('appointment');}} />}</div>;
}

function Stat({ label, value, sub, icon, compact=false }: { label:string; value:string; sub:string; icon:React.ReactNode; compact?:boolean }) { return <div className="stat-card"><div className="stat-top"><span>{label}</span><div>{icon}</div></div><strong className={compact?'compact':''}>{value}</strong><small>{sub}</small><Skull className="stat-watermark"/></div>; }

function EditorModal({ type, editingService, editingBarber, barbers, services, clients, memberships, day, onClose, onSaved, onClientCreated }: { type:'appointment'|'service'|'barber'|'client'; editingService:Service|null; editingBarber:User|null; barbers:User[]; services:Service[]; clients:Client[]; memberships:Membership[]; day:string; onClose:()=>void; onSaved:(message:string)=>void; onClientCreated:(client:Client)=>void }) {
  const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const [form,setForm]=useState<Record<string,string>>({ name: type==='service'?editingService?.name||'':type==='barber'?editingBarber?.name||'':'', email:editingBarber?.email||'', phone:editingBarber?.phone||'', description:editingService?.description||'', duration:String(editingService?.duration||45), price:String(editingService?.price||''), commission:String(editingBarber?.commission||40), workStart:editingBarber?.workStart||'09:00', workEnd:editingBarber?.workEnd||'19:00', password:'', date:day, time:'09:00', barberId:barbers[0]?.id||'', clientId:clients[0]?.id||'', serviceId:services[0]?.id||'', subscriptionId:'' });
  const period = form.date.slice(0,7);
  const eligibleMemberships = memberships.filter(m=>m.clientId===form.clientId && m.status==='ATIVA' && m.includedServices.some(s=>s.id===form.serviceId) && m.visitsUsed<m.visitsPerMonth && m.payments.some(p=>p.period===period && p.status==='PAGO'));
  const set=(key:string)=>(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>)=>setForm(f=>({...f,[key]:e.target.value}));
  async function submit(e:React.FormEvent) { e.preventDefault(); setBusy(true); setError(''); try {
    if(type==='service') { await request(`/services${editingService?`/${editingService.id}`:''}`, {method:editingService?'PUT':'POST',body:JSON.stringify({name:form.name,description:form.description,duration:Number(form.duration),price:Number(form.price)})}); onSaved(editingService?'Serviço atualizado.':'Serviço criado.'); }
    if(type==='barber') { const body:Record<string,string|number>={name:form.name,email:form.email,phone:form.phone,commission:Number(form.commission),workStart:form.workStart,workEnd:form.workEnd}; if(!editingBarber)body.password=form.password; await request(`/users${editingBarber?`/${editingBarber.id}`:''}`,{method:editingBarber?'PATCH':'POST',body:JSON.stringify(body)});onSaved(editingBarber?'Profissional atualizado.':'Profissional cadastrado.'); }
    if(type==='client') { const client=await request<Client>('/clients',{method:'POST',body:JSON.stringify({name:form.name,phone:form.phone})});onClientCreated(client); }
    if(type==='appointment') { if(!form.clientId)throw new Error('Cadastre ou selecione um cliente.'); await request('/appointments',{method:'POST',body:JSON.stringify({date:new Date(`${form.date}T${form.time}:00`).toISOString(),barberId:form.barberId,clientId:form.clientId,serviceId:form.serviceId,...(form.subscriptionId?{subscriptionId:form.subscriptionId}:{})})});onSaved('Agendamento criado.'); }
  } catch(e){setError((e as Error).message);} finally{setBusy(false);} }
  const title=type==='service'?(editingService?'Editar serviço':'Novo serviço'):type==='barber'?(editingBarber?'Editar barbeiro':'Novo barbeiro'):type==='client'?'Novo cliente':'Novo agendamento';
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal"><div className="modal-head"><div><div className="eyebrow"><span className="eyebrow-line"/> BARBERFLOW</div><h2>{title}</h2></div><button className="close-modal" onClick={onClose} aria-label="Fechar"><X size={22}/></button></div><form onSubmit={submit} className="modal-form">
  {(type==='service'||type==='barber'||type==='client') && <label>Nome<input value={form.name} onChange={set('name')} required minLength={2} placeholder={type==='service'?'Ex.: Corte clássico':'Nome completo'}/></label>}
  {type==='service' && <><label>Descrição<textarea value={form.description} onChange={set('description')} placeholder="O que está incluído no atendimento?" rows={3}/></label><div className="form-two"><label>Duração (min)<input type="number" min="5" max="480" value={form.duration} onChange={set('duration')} required/></label><label>Preço (R$)<input type="number" min="0" step="0.01" value={form.price} onChange={set('price')} required/></label></div></>}
  {type==='barber' && <><label>E-mail<input type="email" value={form.email} onChange={set('email')} required placeholder="profissional@email.com"/></label><label>Telefone<input value={form.phone} onChange={set('phone')} placeholder="(00) 00000-0000"/></label>{!editingBarber && <label>Senha inicial (mín. 12 caracteres)<input type="password" value={form.password} onChange={set('password')} minLength={12} required autoComplete="new-password"/></label>}<div className="form-two"><label>Início do expediente<input type="time" value={form.workStart} onChange={set('workStart')} required/></label><label>Fim do expediente<input type="time" value={form.workEnd} onChange={set('workEnd')} required/></label></div><label>Comissão (%)<input type="number" min="0" max="100" step="0.01" value={form.commission} onChange={set('commission')} required/></label></>}
  {type==='client' && <label>Telefone<input value={form.phone} onChange={set('phone')} placeholder="(00) 00000-0000"/></label>}
  {type==='appointment' && <><label>Cliente<div className="select-with-action"><select value={form.clientId} onChange={e=>setForm(f=>({...f,clientId:e.target.value,subscriptionId:''}))} required><option value="">Selecione um cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button type="button" onClick={()=>{onClose();setTimeout(()=>document.dispatchEvent(new CustomEvent('barberflow:new-client')),0);}} title="Novo cliente"><Plus size={18}/></button></div></label><label>Barbeiro<select value={form.barberId} onChange={set('barberId')} required>{barbers.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Serviço<select value={form.serviceId} onChange={e=>setForm(f=>({...f,serviceId:e.target.value,subscriptionId:''}))} required>{services.map(s=><option key={s.id} value={s.id}>{s.name} · {money(s.price)}</option>)}</select></label><div className="form-two"><label>Data<input type="date" value={form.date} onChange={e=>setForm(f=>({...f,date:e.target.value,subscriptionId:''}))} required/></label><label>Horário<input type="time" value={form.time} onChange={set('time')} required/></label></div><label>Forma de atendimento<select value={form.subscriptionId} onChange={set('subscriptionId')}><option value="">Avulso · cobrar {money(services.find(s=>s.id===form.serviceId)?.price||0)}</option>{eligibleMemberships.map(m=><option key={m.id} value={m.id}>{m.plan.name} · {m.visitsUsed}/{m.visitsPerMonth} usados no mês</option>)}</select></label>{!eligibleMemberships.length&&<p className="modal-hint">Assinaturas aparecem aqui quando o cliente tem mensalidade paga, serviço incluído e saldo de atendimentos.</p>}</>}
  {error && <p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="button button-secondary" onClick={onClose}>Cancelar</button><button className="button button-primary" disabled={busy}>{busy?'Salvando...':'Salvar'}<ArrowRight size={17}/></button></div></form></div></div>;
}
