'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Banknote, CalendarOff, CheckCircle2, History, MessageCircle, Plus, ReceiptText, Trash2, Wallet } from 'lucide-react';
import { money, request } from '../lib/api';

type Summary={revenue:number;expenseTotal:number;balance:number;byPaymentMethod:{method:string;total:number}[];expenses:{id:string;description:string;category:string;amount:number;date:string;paymentMethod:string}[];closings:{id:string;businessDate:string;expectedAmount:number;actualAmount:number;difference:number}[]};
type Barber={id:string;name:string;role:string}; type Client={id:string;name:string}; type Block={id:string;start:string;end:string;reason:string;barber:{name:string}};
const today=()=>new Date().toISOString().slice(0,10); const methodLabels:Record<string,string>={DINHEIRO:'Dinheiro',PIX:'PIX',CARTAO_CREDITO:'Cartão de crédito',CARTAO_DEBITO:'Cartão de débito',OUTRO:'Outro'};
const range=()=>{const n=new Date();return{from:new Date(n.getFullYear(),n.getMonth(),1).toISOString(),to:new Date(n.getFullYear(),n.getMonth()+1,1).toISOString()}};

export default function Operations(){
 const [summary,setSummary]=useState<Summary|null>(null);const[barbers,setBarbers]=useState<Barber[]>([]);const[clients,setClients]=useState<Client[]>([]);const[blocks,setBlocks]=useState<Block[]>([]);const[history,setHistory]=useState<any>(null);const[error,setError]=useState('');const[notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const q=new URLSearchParams(range()).toString();try{const[s,u,c,b]=await Promise.all([request<Summary>(`/operations/summary?${q}`),request<Barber[]>('/users'),request<Client[]>('/clients'),request<Block[]>(`/schedule-blocks?${q}`)]);setSummary(s);setBarbers(u.filter(x=>x.role==='BARBEIRO'));setClients(c);setBlocks(b);}catch(e){setError((e as Error).message)}},[]);useEffect(()=>{void load()},[load]);
 async function submitExpense(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await request('/expenses',{method:'POST',body:JSON.stringify({description:f.get('description'),category:f.get('category'),amount:Number(f.get('amount')),date:new Date(`${f.get('date')}T12:00:00`).toISOString(),paymentMethod:f.get('paymentMethod')})});e.currentTarget.reset();setNotice('Despesa registrada.');await load()}catch(x){setError((x as Error).message)}finally{setBusy(false)}}
 async function submitBlock(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await request('/schedule-blocks',{method:'POST',body:JSON.stringify({barberId:f.get('barberId'),start:new Date(String(f.get('start'))).toISOString(),end:new Date(String(f.get('end'))).toISOString(),reason:f.get('reason')})});e.currentTarget.reset();setNotice('Indisponibilidade adicionada.');await load()}catch(x){setError((x as Error).message)}finally{setBusy(false)}}
 async function submitClosing(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await request('/cash-closings',{method:'POST',body:JSON.stringify({businessDate:f.get('businessDate'),openingAmount:Number(f.get('openingAmount')),actualAmount:Number(f.get('actualAmount')),notes:f.get('notes')||undefined})});e.currentTarget.reset();setNotice('Caixa fechado com sucesso.');await load()}catch(x){setError((x as Error).message)}finally{setBusy(false)}}
 async function clientHistory(id:string){if(!id){setHistory(null);return}try{setHistory(await request(`/clients/${id}/history`))}catch(x){setError((x as Error).message)}}
 async function reminders(){try{const r=await request<{processed:number;sent:number;skipped:number;failed:number}>('/reminders/process',{method:'POST'});setNotice(`${r.processed} lembretes processados: ${r.sent} enviados, ${r.skipped} aguardando configuração e ${r.failed} falharam.`)}catch(x){setError((x as Error).message)}}
 const field='rounded-lg border border-[#333] bg-[#181818] px-3 py-2 text-sm text-white';
 return <div className="space-y-5 pb-12">{error&&<div className="alert error">{error}<button onClick={()=>setError('')}>×</button></div>}{notice&&<div className="alert success">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
 <div className="grid gap-3 sm:grid-cols-3"><Metric label="RECEITAS DO MÊS" value={money(summary?.revenue||0)} icon={<Wallet/>}/><Metric label="DESPESAS DO MÊS" value={money(summary?.expenseTotal||0)} icon={<ReceiptText/>}/><Metric label="SALDO OPERACIONAL" value={money(summary?.balance||0)} icon={<Banknote/>}/></div>
 <div className="grid gap-4 xl:grid-cols-2"><Panel title="Registrar despesa" icon={<ReceiptText/>}><form onSubmit={submitExpense} className="grid gap-3 sm:grid-cols-2"><input className={field} name="description" placeholder="Descrição" required/><input className={field} name="category" placeholder="Categoria" required/><input className={field} name="amount" type="number" min="0.01" step="0.01" placeholder="Valor" required/><input className={field} name="date" type="date" defaultValue={today()} required/><select className={field} name="paymentMethod">{Object.entries(methodLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button disabled={busy} className="button button-primary"><Plus size={16}/>Adicionar</button></form></Panel>
 <Panel title="Fechamento diário" icon={<CheckCircle2/>}><form onSubmit={submitClosing} className="grid gap-3 sm:grid-cols-2"><input className={field} name="businessDate" type="date" defaultValue={today()} required/><input className={field} name="openingAmount" type="number" min="0" step="0.01" placeholder="Fundo inicial" required/><input className={field} name="actualAmount" type="number" min="0" step="0.01" placeholder="Valor contado" required/><input className={field} name="notes" placeholder="Observações"/><button disabled={busy} className="button button-primary sm:col-span-2">Fechar caixa</button></form>{summary?.closings?.slice(0,3).map(x=><div key={x.id} className="mt-3 flex justify-between border-t border-[#292929] pt-3 text-xs"><span>{x.businessDate.split('-').reverse().join('/')}</span><span>Diferença: <b className={Number(x.difference)===0?'text-[#84ba90]':'text-[#d7b47b]'}>{money(x.difference)}</b></span></div>)}</Panel></div>
 <div className="grid gap-4 xl:grid-cols-2"><Panel title="Folgas e bloqueios" icon={<CalendarOff/>}><form onSubmit={submitBlock} className="grid gap-3 sm:grid-cols-2"><select className={field} name="barberId" required><option value="">Barbeiro</option>{barbers.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input className={field} name="reason" placeholder="Motivo" required/><input className={field} name="start" type="datetime-local" required/><input className={field} name="end" type="datetime-local" required/><button className="button button-primary sm:col-span-2" disabled={busy}>Bloquear horário</button></form><div className="mt-4 space-y-2">{blocks.map(b=><div key={b.id} className="flex items-center gap-3 rounded-lg bg-[#191919] p-3 text-xs"><div className="flex-1"><b>{b.barber.name}</b><div className="text-[#92918c]">{new Date(b.start).toLocaleString('pt-BR')} · {b.reason}</div></div><button aria-label="Excluir bloqueio" onClick={async()=>{await request(`/schedule-blocks/${b.id}`,{method:'DELETE'});await load()}}><Trash2 size={15}/></button></div>)}</div></Panel>
 <Panel title="Histórico do cliente" icon={<History/>}><select className={`${field} w-full`} onChange={e=>void clientHistory(e.target.value)}><option value="">Selecione um cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{history&&<div className="mt-4"><div className="mb-3 text-sm"><b>{history.name}</b><p className="text-xs text-[#92918c]">{history.phone||'Sem telefone'} · {history.appointments.length} atendimentos</p></div><div className="max-h-56 space-y-2 overflow-auto">{history.appointments.map((a:any)=><div key={a.id} className="rounded-lg bg-[#191919] p-3 text-xs"><b>{a.service.name}</b><div className="text-[#92918c]">{new Date(a.date).toLocaleString('pt-BR')} · {a.barber.name} · {a.status}</div></div>)}</div></div>}<button onClick={reminders} className="button button-secondary mt-4 w-full"><MessageCircle size={16}/>Processar lembretes WhatsApp</button></Panel></div>
 <Panel title="Fluxo por forma de pagamento" icon={<Banknote/>}><div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-5">{summary?.byPaymentMethod.map(x=><div key={x.method} className="rounded-lg bg-[#191919] p-3"><small className="text-[#92918c]">{methodLabels[x.method]||x.method}</small><strong className="mt-1 block">{money(x.total)}</strong></div>)}</div></Panel></div>}
function Metric({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <div className="stat-card"><div className="stat-top"><span>{label}</span><div>{icon}</div></div><strong className="compact">{value}</strong><small>período atual</small></div>}
function Panel({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="rounded-xl border border-[#292929] bg-[#121212] p-5"><div className="mb-4 flex items-center justify-between"><h2 className="m-0 text-2xl">{title}</h2><span className="text-[#d7b47b]">{icon}</span></div>{children}</section>}
