'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowRight, BadgeCheck, CalendarClock, Check, CreditCard, Pause, Pencil, Play, Plus, Search, Trash2, UsersRound, X } from 'lucide-react';
import { money, request } from '../lib/api';

type Plan = { id: string; name: string; description?: string; price: number | string; visitsPerMonth: number; services: { id: string; name: string }[]; _count?: { subscriptions: number } };
type Client = { id: string; name: string; phone?: string };
type Service = { id: string; name: string };
type Payment = { id: string; period: string; dueDate: string; amount: number | string; status: 'PENDENTE' | 'PAGO'; paidAt?: string };
type Subscription = { id: string; status: 'ATIVA' | 'PAUSADA' | 'CANCELADA'; price: number | string; billingDay: number; startDate: string; visitsPerMonth: number; visitsUsed: number; client: Client; plan: Plan; payments: Payment[] };
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const period = () => today().slice(0,7);
const dateText = (iso: string) => new Date(iso).toLocaleDateString('pt-BR');

export default function Subscriptions() {
  const [plans, setPlans] = useState<Plan[]>([]); const [subs, setSubs] = useState<Subscription[]>([]); const [clients, setClients] = useState<Client[]>([]); const [services, setServices] = useState<Service[]>([]);
  const [modal, setModal] = useState<'plan'|'subscription'|'client'|null>(null); const [editing, setEditing] = useState<Plan|null>(null);
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState<'TODAS'|'ATIVA'|'PAUSADA'|'CANCELADA'>('TODAS');
  const [form, setForm] = useState({ name:'', description:'', price:'', visitsPerMonth:'1', clientId:'', planId:'', startDate:today(), billingDay:String(Math.min(28, new Date().getDate())), phone:'' });
  const [selectedServices, setSelectedServices] = useState<string[]>([]);
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const [p,s,c,v] = await Promise.all([request<Plan[]>('/subscription-plans'),request<Subscription[]>('/subscriptions'),request<Client[]>('/clients'),request<Service[]>('/services')]);setPlans(p);setSubs(s);setClients(c);setServices(v);setError(''); } catch(e){setError((e as Error).message);} finally{setLoading(false);} }, []);
  useEffect(() => { load(); }, [load]);
  const active = subs.filter(s => s.status === 'ATIVA');
  const pending = subs.flatMap(s => s.payments.map(p => ({...p,client:s.client.name,plan:s.plan.name}))).filter(p => p.status==='PENDENTE').sort((a,b)=>a.dueDate.localeCompare(b.dueDate));
  const overdue = pending.filter(p=>new Date(p.dueDate).getTime()<Date.now());
  const paidMonth = subs.flatMap(s=>s.payments).filter(p=>p.status==='PAGO' && p.paidAt?.slice(0,7)===period()).reduce((sum,p)=>sum+Number(p.amount),0);
  const filtered = useMemo(()=>subs.filter(s=>(filter==='TODAS'||s.status===filter) && `${s.client.name} ${s.plan.name}`.toLowerCase().includes(query.toLowerCase())),[subs,filter,query]);
  const patch=(key:keyof typeof form)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm(v=>({...v,[key]:e.target.value}));
  function openPlan(plan:Plan|null=null){setEditing(plan);setForm(v=>({...v,name:plan?.name||'',description:plan?.description||'',price:plan?String(plan.price):'',visitsPerMonth:String(plan?.visitsPerMonth||1)}));setSelectedServices(plan?.services.map(s=>s.id)||[]);setModal('plan');}
  function openSubscription(){setForm(v=>({...v,clientId:clients[0]?.id||'',planId:plans[0]?.id||'',startDate:today(),billingDay:String(Math.min(28,new Date().getDate()))}));setModal('subscription');}
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{
    if(modal==='plan'){if(!selectedServices.length)throw new Error('Selecione ao menos um serviço incluído.');await request(`/subscription-plans${editing?`/${editing.id}`:''}`,{method:editing?'PUT':'POST',body:JSON.stringify({name:form.name,description:form.description,price:Number(form.price),visitsPerMonth:Number(form.visitsPerMonth),serviceIds:selectedServices})});setNotice(editing?'Plano atualizado.':'Plano criado.');}
    if(modal==='client'){const client=await request<Client>('/clients',{method:'POST',body:JSON.stringify({name:form.name,phone:form.phone})});setClients(v=>[...v,client]);setForm(v=>({...v,clientId:client.id}));setNotice('Cliente cadastrado.');setModal('subscription');await load();return;}
    if(modal==='subscription'){await request('/subscriptions',{method:'POST',body:JSON.stringify({clientId:form.clientId,planId:form.planId,startDate:new Date(`${form.startDate}T12:00:00`).toISOString(),billingDay:Number(form.billingDay)})});setNotice('Assinatura criada.');}
    setModal(null);await load();
  }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function changeStatus(s:Subscription,status:Subscription['status']){if(status==='CANCELADA'&&!confirm(`Cancelar a assinatura de ${s.client.name}?`))return;try{await request(`/subscriptions/${s.id}`,{method:'PATCH',body:JSON.stringify({status})});setNotice(status==='ATIVA'?'Assinatura reativada.':status==='PAUSADA'?'Assinatura pausada.':'Assinatura cancelada.');await load();}catch(e){setError((e as Error).message);}}
  async function pay(p:Payment,undo=false){try{await request(`/subscription-payments/${p.id}/${undo?'reopen':'pay'}`,{method:'POST'});setNotice(undo?'Pagamento reaberto.':'Pagamento registrado.');await load();}catch(e){setError((e as Error).message);}}
  async function archive(plan:Plan){if(!confirm(`Arquivar o plano ${plan.name}? Assinaturas existentes continuam válidas.`))return;try{await request(`/subscription-plans/${plan.id}`,{method:'DELETE'});setNotice('Plano arquivado.');await load();}catch(e){setError((e as Error).message);}}
  return <div className="subscriptions-page">
    {error&&<div className="alert error">{error}<button onClick={()=>setError('')}><X size={16}/></button></div>}{notice&&<div className="alert success">{notice}<button onClick={()=>setNotice('')}><X size={16}/></button></div>}
    <div className="subscription-actions"><div className="subscription-description"><BadgeCheck size={18}/><span>Receita recorrente, clientes fiéis.</span></div><div><button className="button button-secondary" onClick={()=>openPlan()}><Plus size={16}/> Novo plano</button><button className="button button-primary" onClick={openSubscription} disabled={!plans.length}><Plus size={16}/> Nova assinatura</button></div></div>
    <div className="subscription-stats"><div><small>ASSINATURAS ATIVAS</small><strong>{active.length.toString().padStart(2,'0')}</strong><span>clientes no clube</span><UsersRound size={25}/></div><div><small>RECORRÊNCIA PREVISTA / MÊS</small><strong>{money(active.reduce((sum,s)=>sum+Number(s.price),0))}</strong><span>valor das assinaturas ativas</span><CalendarClock size={25}/></div><div><small>RECEBIDO NESTE MÊS</small><strong>{money(paidMonth)}</strong><span>mensalidades confirmadas</span><CreditCard size={25}/></div><div className={overdue.length?'overdue':''}><small>COBRANÇAS EM ATRASO</small><strong>{overdue.length.toString().padStart(2,'0')}</strong><span>{pending.length} pendente{pending.length!==1?'s':''} no total</span><CalendarClock size={25}/></div></div>
    <div className="section-title"><div><h2>Planos da casa</h2><p>Valores mensais para uma rotina de cuidado</p></div><span>{plans.length} PLANO{plans.length!==1?'S':''}</span></div>
    <div className="plan-grid">{plans.map((plan,i)=><article className="plan-card" key={plan.id}><div className="plan-top"><span>PLANO 0{i+1}</span><BadgeCheck size={21}/></div><h3>{plan.name}</h3><p>{plan.description||'Um plano para cuidar do visual o mês inteiro.'}</p><div className="plan-includes"><strong>{plan.visitsPerMonth} atendimento{plan.visitsPerMonth!==1?'s':''} / mês</strong><span>{plan.services.map(s=>s.name).join(' · ')}</span></div><div className="plan-price"><strong>{money(plan.price)}</strong><span>/ mês</span></div><div className="plan-bottom"><small>{plan._count?.subscriptions||0} assinatura{plan._count?.subscriptions===1?'':'s'} registrada{plan._count?.subscriptions===1?'':'s'}</small><div><button onClick={()=>openPlan(plan)} aria-label={`Editar ${plan.name}`}><Pencil size={16}/></button><button onClick={()=>archive(plan)} aria-label={`Arquivar ${plan.name}`}><Trash2 size={16}/></button></div></div></article>)}{!plans.length&&!loading&&<div className="empty-wide"><BadgeCheck size={30}/><h3>Crie seu primeiro plano</h3><p>Defina um valor mensal e comece a cadastrar assinantes.</p><button className="button button-secondary" onClick={()=>openPlan()}>Criar plano</button></div>}</div>
    <div className="section-title subscription-section"><div><h2>Assinantes</h2><p>Acompanhe o status de cada cliente</p></div><span>{subs.length} CADASTRADO{subs.length!==1?'S':''}</span></div>
    <div className="subscriber-toolbar"><div className="subscriber-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente ou plano..."/></div><div className="filter-chips">{(['TODAS','ATIVA','PAUSADA','CANCELADA'] as const).map(value=><button key={value} className={filter===value?'selected':''} onClick={()=>setFilter(value)}>{value==='TODAS'?'Todas':value==='ATIVA'?'Ativas':value==='PAUSADA'?'Pausadas':'Canceladas'}</button>)}</div></div>
    <div className="subscriber-list">{filtered.map(s=>{const invoice=s.payments.find(p=>p.period===period())||s.payments[0];return <article className="subscriber-row" key={s.id}><div className="subscriber-avatar">{s.client.name.slice(0,1)}</div><div className="subscriber-name"><strong>{s.client.name}</strong><span>{s.plan.name} · {s.visitsUsed}/{s.visitsPerMonth} atendimentos no mês · cobrança dia {s.billingDay}</span></div><div className="subscriber-value"><strong>{money(s.price)}</strong><small>mensal</small></div><div className="subscriber-payment">{invoice?<span className={`payment-badge ${invoice.status==='PAGO'?'paid':new Date(invoice.dueDate)<new Date()?'late':'pending'}`}>{invoice.status==='PAGO'?'Pago':new Date(invoice.dueDate)<new Date()?'Atrasado':'Pendente'}</span>:<span className="payment-badge pending">A iniciar</span>}<small>{invoice?`Vence ${dateText(invoice.dueDate)}`:`Início ${dateText(s.startDate)}`}</small></div><span className={`subscriber-status ${s.status.toLowerCase()}`}>{s.status==='ATIVA'?'Ativa':s.status==='PAUSADA'?'Pausada':'Cancelada'}</span><div className="subscriber-controls">{invoice&&invoice.status==='PENDENTE'&&<button className="pay-button" onClick={()=>pay(invoice)} title="Registrar pagamento"><Check size={16}/> Receber</button>}{invoice&&invoice.status==='PAGO'&&<button className="control-icon" onClick={()=>pay(invoice,true)} title="Reabrir pagamento"><CreditCard size={16}/></button>}{s.status==='ATIVA'?<button className="control-icon" onClick={()=>changeStatus(s,'PAUSADA')} title="Pausar"><Pause size={16}/></button>:s.status==='PAUSADA'?<button className="control-icon" onClick={()=>changeStatus(s,'ATIVA')} title="Reativar"><Play size={16}/></button>:null}{s.status!=='CANCELADA'&&<button className="control-icon danger" onClick={()=>changeStatus(s,'CANCELADA')} title="Cancelar"><X size={16}/></button>}</div></article>})}{!filtered.length&&<div className="empty-wide"><UsersRound size={29}/><h3>{subs.length?'Nenhum resultado':'Ainda não há assinantes'}</h3><p>{subs.length?'Tente outra busca ou filtro.':'Cadastre o primeiro cliente em um plano mensal.'}</p></div>}</div>
    <div className="section-title subscription-section"><div><h2>Cobranças pendentes</h2><p>Mensalidades que aguardam confirmação manual</p></div><span>{pending.length} PENDENTE{pending.length!==1?'S':''}</span></div><div className="pending-list">{pending.slice(0,8).map(p=><div className="pending-row" key={p.id}><div className="pending-icon"><CreditCard size={18}/></div><div><strong>{p.client}</strong><small>{p.plan} · referência {p.period} · vencimento {dateText(p.dueDate)}</small></div><b>{money(p.amount)}</b><button className="button button-secondary" onClick={()=>pay(p)}><Check size={15}/> Registrar pagamento</button></div>)}{!pending.length&&<div className="empty-mini">Tudo em dia. Nenhuma cobrança pendente.</div>}</div>
    {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null);}}><div className="modal"><div className="modal-head"><div><div className="eyebrow"><span className="eyebrow-line"/> CLUBE BARBERFLOW</div><h2>{modal==='plan'?(editing?'Editar plano':'Novo plano'):modal==='client'?'Novo cliente':'Nova assinatura'}</h2></div><button className="close-modal" onClick={()=>setModal(null)} aria-label="Fechar"><X size={21}/></button></div><form className="modal-form" onSubmit={submit}>
      {(modal==='plan'||modal==='client')&&<label>Nome<input value={form.name} onChange={patch('name')} minLength={2} required placeholder={modal==='plan'?'Ex.: Clube Clássico':'Nome do cliente'}/></label>}
      {modal==='plan'&&<><label>Descrição<textarea value={form.description} onChange={patch('description')} rows={3} placeholder="O que o plano oferece?"/></label><div className="form-two"><label>Mensalidade (R$)<input type="number" min="0.01" step="0.01" value={form.price} onChange={patch('price')} required/></label><label>Atendimentos / mês<input type="number" min="1" max="31" value={form.visitsPerMonth} onChange={patch('visitsPerMonth')} required/></label></div><div className="included-services"><strong>SERVIÇOS INCLUÍDOS</strong>{services.map(s=><label key={s.id}><input type="checkbox" checked={selectedServices.includes(s.id)} onChange={e=>setSelectedServices(v=>e.target.checked?[...v,s.id]:v.filter(id=>id!==s.id))}/>{s.name}</label>)}{!services.length&&<span>Cadastre serviços antes de criar um plano.</span>}</div><p className="modal-hint">Mudanças no plano valem para novas assinaturas. Assinantes existentes mantêm as condições contratadas.</p></>}
      {modal==='client'&&<label>Telefone<input value={form.phone} onChange={patch('phone')} placeholder="(00) 00000-0000"/></label>}
      {modal==='subscription'&&<><label>Cliente<div className="select-with-action"><select value={form.clientId} onChange={patch('clientId')} required><option value="">Selecione</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button type="button" onClick={()=>{setForm(v=>({...v,name:'',phone:''}));setModal('client');}} title="Cadastrar cliente"><Plus size={18}/></button></div></label><label>Plano<select value={form.planId} onChange={patch('planId')} required><option value="">Selecione</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name} · {money(p.price)}/mês</option>)}</select></label><div className="form-two"><label>Início<input type="date" value={form.startDate} onChange={patch('startDate')} required/></label><label>Dia de cobrança<input type="number" min="1" max="28" value={form.billingDay} onChange={patch('billingDay')} required/></label></div><p className="modal-hint">Pagamentos são registrados manualmente. A cobrança do mês é criada automaticamente quando a assinatura estiver ativa.</p></>}
      {error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="button button-secondary" onClick={()=>setModal(null)}>Cancelar</button><button className="button button-primary" disabled={busy}>{busy?'Salvando...':'Salvar'}<ArrowRight size={16}/></button></div></form></div></div>}
  </div>;
}
